### ISSUE TITLE
🚀 Feature Request: Add support for pplx api

### ISSUE THREAD

**Issue by hiuxia** [tisfeng/Easydict#254] opened 2023-12-05 09:05 UTC
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page and didn't find a similar feature request.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)

### Feature description

Add support for [perplexity ai](https://docs.perplexity.ai/) for translation support, like openai api. 
> - The price is cheaper 
> - Has online module on its in-house 7b and 70b module.

### Use case (optional)

Here are a few preliminary, very unmature ideas:
- translate the sentence 
- explain the grammar, structure of the sentence.
- expand the selected sentence 
- Besides, I hope in the future we can integrate with **Anki**, which is the most effective tool for learning language, by using `Ankiconnect`.

### Proposed solution (optional)

I can provide the an api key($5) and help testing the prompt. Besides I think [pplx playground](https://labs.perplexity.ai/) is the best place to try this Api. 

### Are you willing to submit a PR to implement this feature

- [ ] I'm willing to submit PR

**Comment by tisfeng** [comment] 2023-12-06 03:32
Why did you close it?

I haven't had a chance to learn about [perplexity ai](https://docs.perplexity.ai/) , which looks like it's also an OpenAI-like service, what's wrong with it?

**Comment by hiuxia** [comment] 2023-12-06 03:44
Sorry for this my stupid misunderstanding. I just think that this request maybe require too much work for you(捂脸）.

**Comment by hiuxia** [comment] 2023-12-06 03:52
Perplexity is a wonderful third party LLM service that integrates GPT4, claude 2.1 and other functions like image search, generation, video search; It also supports personal prompt for each of your thread by assigning them to collections. 

Besides, it provides up to 600 GPT4 and claude 2.1 usage with rapid Internet search(offline is also supported). It also provides $5 quota api for its pro users(which is 20$ like chatgpt), but It always have some coupons like two months free for new subscribers. 

> This is not an ad.

**Comment by hiuxia** [comment] 2023-12-06 04:02
The reason why I would like to open this issue is that I think this wonderful macos application can definitely serve as an language learning hub (especially for English). With such a beautful UI and excellent design, I think this app can be used to bridge the gap between different different scenarios:
- reading English learning materials and then explain the vocabulary.
- Ask AI to explain the concepts and then send them to notes app combined with apps like `popclip` and `obsidian`
- select code samples and then ask AI to explain its usage.

> Very unmature idea: Maybe this app can not only be used as language dictionary, but also for other aims, like language learning and code explanation.

**Comment by hiuxia** [comment] 2023-12-06 04:04
Because of my own capacity constraints, I can't make a PR by myself. But I will try my best to help you If you have relevant ideas.

**Comment by hiuxia** [comment] 2023-12-06 14:10
I have checked one api already and there are already an issue about pplx api integration. Any way, thank you for the support.

**Comment by tisfeng** [comment] 2023-12-06 14:19
> Maybe this app can not only be used as language dictionary, but also for other aims, like language learning and code explanation.

Good idea, I've been thinking about it. The problem is that we don't have enough developers in our team, and more importantly, I'm not good at doing some complex feature design and the corresponding UI design. 

On the other hand, I have a high demand for new features, and I want the app to be simple and elegant while still being powerful.

**Comment by hiuxia** [comment] 2023-12-06 14:53
So I think a useful plugin system can be pretty useful. At least I think maybe we can extract the APIs to module like other similar app like Bob, and by such way people can surely implement the features more easily and you can save a lot of laborious job.

**Comment by hiuxia** [comment] 2023-12-06 14:58
Recently I wrote quiet a few popclip addons and I found they emancipated me from all kinds of tedious jobs. **Basically, I think any text processing app would double their productivity with a well designed addon system**, the most famous example should be vscode.

**Comment by tisfeng** [comment] 2023-12-06 15:34
I understand that at first I thought Easydict was an open source application that everyone could come to PR, so there was no need to have an open plugin system like Bob must have.

But later I realized that the number of developers who can write objc or Swift is too small compared to the number of developers who can write JS, so if I can make a JS plugin system, it can greatly enrich the ecosystem of Easydict. 

However, my JS level is very low, I'm afraid I can't design a powerful plugin system similar to PopClip, so I've put it on hold 😔

**Closed** 2023-12-07 04:46 UTC
Labels: enhancement
