### ISSUE TITLE
🐞 Bug Report: OCR translation has stopped working

### ISSUE THREAD

**Issue by thesla13** [tisfeng/Easydict#128] opened 2023-06-19 10:00 UTC
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the latest version.

### Problem description

Hello, Tisfeng!

Recently, since about two to three weeks ago, OCR screenshot translate has started working weirdly for me. 

Almost every time I use OCR, the EasyDict's translation window appears, but gets forever stuck in the recognition process.

However many times would I try again — it still gets stuck. Then I would quit the app, relaunch it, and the OCR would work — for _exactly_one_time!

I've even created a script in BetterTouchTools that with one keyboard shortcut quits EasyDict, relaunches it, and initiates screenshot translating, so every use would be the first attempt. That works fine, but I guess it's not the intended way to use the app.
![Snipaste_2023-06-19_12-51-01](https://github.com/tisfeng/Easydict/assets/55979516/e7548181-caed-47df-a333-b7ca1eb42f60)

### Reproduction steps

1. I initiate screenshot translating with a shortcut. 
2. EasyDict's window appeares.
3. Nothing ever happens.

### Expected result

A successful text recognition, I would guess ))

### Device information and OS version (optional)

Apple MPB 16", M1 Max, macOS 13.5

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR!

**Comment by thesla13** [comment] 2023-06-19 10:04
Oh, and yes, since the time it stopped working, I've updated the app to the latest version at least once. Nothing changed. And I have changed nothing in my internet configuration. The OCR doesn't work neither with VPN nor without it.

**Comment by Jerry23011** [comment] 2023-06-19 14:16
Hi, @thesla13, could you please confirm your Easydict version? Is it the latest one? (1.3.4)

Also, I noticed that you are using macOS beta (13.5). This problem could be caused by the instability of the beta version because Easydict adopts the integrated text recognition of macOS, so it doesn't require an internet connection.

Finally, please export the logs of Easydict after the issue occurs
<img width="380" alt="截屏2023-06-19 22 15 43" src="https://github.com/tisfeng/Easydict/assets/89069957/31ea19e4-d125-498a-a0d7-fe0c7b68490e">

**Comment by tisfeng** [comment] 2023-06-19 15:44
Have you tried "Silent Screenshot OCR" ? Is this feat working properly?

**Comment by thesla13** [comment] 2023-08-22 12:19
Hey, tisfeng and Jerry!

I'm so sorry for the much belated reply, I've completely missed the notifications about your posts.

As for the issue I've had — it has resolved by itself somehow, a couple of weeks ago. Now everything seems to work perfectly, even after an update to Sonoma beta.

Thank you once again for the incredible app!

**Comment by Jerry23011** [comment] 2023-08-22 12:21
Thanks for the feedback, @thesla13. I'll close this now :)

**Closed by Jerry23011** 2023-08-22 12:21 UTC
Labels: bug, need more info
