### ISSUE TITLE
updating to 2.7 forces to change the app language to chinese and there's no way to change it back to english.

### ISSUE THREAD

**Issue by hyperphysin** [tisfeng/Easydict#528] opened 2024-05-01 02:10 UTC
### Please confirm the following:

- [X] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [X] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

updating to 2.7 forces to change the app language to chinese and there's no way to change it back to english.

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

just update it

### Screenshot

![Screenshot 2024-05-01 at 11 10 09 AM](https://github.com/tisfeng/Easydict/assets/43456637/1490a461-89e0-4bf5-b787-35640c537c17)

### Expected result

I want it to be in english!

### Device type and OS version

apple m2 air, sonoma

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR

**Comment by tisfeng** [comment] 2024-05-01 03:35
Please try to change app language manually.

<img width="820" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/ffe86e2c-ec6b-4121-a94f-b82af7fb0a38">

**Comment by tisfeng** [comment] 2024-05-01 03:52
@choykarl  If you have time, please take a look at this issue and see if it modifies the user's App language?

**Comment by thesla13** [comment] 2024-05-01 04:14
Hey, @tisfeng! I have the same issue @choykarl does.

The thing is the settings page looks nothing like the one in your screenshot. It never did look that way for me in previous versions either. It always looked like this:

![snap 2024 05 01 07-06-25](https://github.com/tisfeng/Easydict/assets/55979516/302eb976-2506-44ba-942b-bf3521432913)

And there doesn't seem to be an option to change the interface language. In your screenshot it's directly above the appearance setting, while there is nothing above the "外观" setting in the layout I happen to have.

I am very much confused, honestly ((

**Comment by tisfeng** [comment] 2024-05-01 12:54
We rewrote the settings page using SwiftUI and added many new features, such as app language switching, but this part of SwiftUI functionality requires macOS 13.0+.

If your computer system is macOS 13.0+, the settings page will have the SwiftUI App option. Please open it and then restart the application.

<img width="584" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/ad98733f-0473-4113-8e24-38f02208191a">

**Comment by Diane-Best** [comment] 2024-05-02 02:44
![image](https://github.com/tisfeng/Easydict/assets/12445472/a8c7d534-d2e6-4c5e-94de-2f940461f2a9)
下载最新版2。7.0安装时 报错

**Comment by tisfeng** [comment] 2024-05-02 02:59
最近我们并没有更改相关的代码，可能是苹果的安全认证又变严格了 🫠

请尝试：设置-隐私与安全性-仍要打开 Easydict

<img width="715" alt="image" src="https://github.com/tisfeng/Easydict/assets/25194972/7843bff1-c027-4da1-9cee-f69a6bf6b5eb">

**Comment by thesla13** [comment] 2024-05-02 07:34
Hey, @tisfeng! Thanks for the reply!

I've switched to the SwiftUI version, it launched in Chinese, but the settings pane became just like in your screenshot, the language switch was right there, and everything is quite perfect now. Thank you!

Except for one minor thing. I use [AltTab](https://github.com/lwouis/alt-tab-macos) window switcher instead of macOS' built-in one. It mimics the way window switching works in Windows listing all the apps' windows instead of switching between apps. And while there is nothing unusual to be seen in Mission Control, AltTab's window switching pane shows a stray faceless window called "Go to Settings" and carrying EasyDict's icon. It's there whenever ED is running: I quit it — the window goes away; launch it again — it reappears.

![snap 2024 05 02 04-19-18](https://github.com/tisfeng/Easydict/assets/55979516/bf31d260-4754-4c3c-b9a8-eec07ea19501)
![snap 2024 05 02 04-22-21](https://github.com/tisfeng/Easydict/assets/55979516/80ac0126-12ab-41cc-b1cc-a38750c39354)


Could you please look into this?

Thank you so much for your hard work!

**Comment by tisfeng** [comment] 2024-05-04 14:32
@thesla13  We've fixed the language issue https://github.com/tisfeng/Easydict/pull/530 .

 I'm not using [AltTab](https://github.com/lwouis/alt-tab-macos), we'll check on this issue later.

**Comment by thesla13** [comment] 2024-05-04 22:02
@tisfeng 

I've looked a bit closer, and it's not just AltTab. The stray interface-less Easydict window is there in Mission Control as well. Admittedly, you have to look for it, but it is there, and for no good reason.

![snap 2024 05 03 02-31-20](https://github.com/tisfeng/Easydict/assets/55979516/be82ae56-41ce-4a26-9a59-d7b4495f2f89)
![snap 2024 05 03 02-02-19](https://github.com/tisfeng/Easydict/assets/55979516/9937f487-d634-41d9-8fde-8b290c2472f2)

**Comment by tisfeng** [comment] 2024-05-05 02:26
Thanks for your feedback, I checked the code and it is indeed a bug, we will fix it later.

**Comment by tisfeng** [comment] 2024-05-07 15:01
The problem is probably caused by this code.  

@AkaShark  Could you take a look at it?

https://github.com/tisfeng/Easydict/blob/d6d04b19d9906fb90b1cd0b71cec6f6cdd496dd1/Easydict/App/EasydictApp.swift#L59

**Comment by AkaShark** [comment] 2024-05-07 16:04
> The problem is probably caused by this code.该问题可能是由这段代码引起的。
> 
> @AkaShark Could you take a look at it? 你能看一下吗？
> 
> https://github.com/tisfeng/Easydict/blob/d6d04b19d9906fb90b1cd0b71cec6f6cdd496dd1/Easydict/App/EasydictApp.swift#L59

Sure, I'll check the code later.

**Comment by tisfeng** [comment] 2024-05-12 15:46
This issue has been fixed in version [2.7.2](https://github.com/tisfeng/Easydict/releases/tag/2.7.2).

**Closed by tisfeng** 2024-05-12 15:46 UTC
Labels: bug, fixed in next release
